version: "3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
  server:
    build: .
    ports: 
      - 8000:8000
    restart: always
    environment:
      PORT: 8000
      DB_URL: postgres://postgres:example@db/postgres?sslmode=disable
      JWT_SECRET: FYyZDmI4wXXSbz71yZaXfHxbBj1t84keiCfai6jZ6WcvJPoKqmenBcaJQPfMqQlMc0au98yBirq3p4oDSnXbcg==
